-- H2 2.3.232;
;             
CREATE USER IF NOT EXISTS "SA" SALT '27ad104a7b157dff' HASH 'c224696e91f3dc143f6ebd34818ab604545ea47cba910ae83276b0778cc910d8' ADMIN;         
CREATE SEQUENCE "PUBLIC"."ESTUDIANTES_SEQ" START WITH 35 RESTART WITH 36;     
CREATE CACHED TABLE "PUBLIC"."USUARIOS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 3) NOT NULL,
    "ACTIVO" BOOLEAN NOT NULL,
    "PASSWORD" CHARACTER VARYING(255) NOT NULL,
    "ROL" CHARACTER VARYING(255) NOT NULL,
    "USERNAME" CHARACTER VARYING(255) NOT NULL
);            
ALTER TABLE "PUBLIC"."USUARIOS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("ID");     
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.USUARIOS;
INSERT INTO "PUBLIC"."USUARIOS" VALUES
(1, TRUE, '$2a$10$kFdbsmvO48jjUkJnkus12uJJQXH9pvZHQvSQ/8LfM3sRTptL56A8W', 'COORDINADOR', 'admin'),
(2, TRUE, '$2a$10$bF/bEZ/BzKeSbG4GTWQijO1X1TR4Jljx0kLr9XHBQag2JYguW/D4u', 'ESTUDIANTE', 'estudiante');            
CREATE CACHED TABLE "PUBLIC"."ESTUDIANTES"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 36) NOT NULL,
    "COMPETENCIAS_CIUDADANAS" INTEGER,
    "COMPETENCIAS_CIUDADANAS_NIVEL" CHARACTER VARYING(255),
    "COMUNICACION_ESCRITA" INTEGER,
    "COMUNICACION_ESCRITA_NIVEL" CHARACTER VARYING(255),
    "CORREO" CHARACTER VARYING(255),
    "DISENO_SOFTWARE" INTEGER,
    "DISENO_SOFTWARE_NIVEL" CHARACTER VARYING(255),
    "DOCUMENTO" CHARACTER VARYING(255) NOT NULL,
    "FORMULACION_PROYECTOS" INTEGER,
    "FORMULACION_PROYECTOS_NIVEL" CHARACTER VARYING(255),
    "INGLES_NIVEL" CHARACTER VARYING(255),
    "LECTURA_CRITICA" INTEGER,
    "LECTURA_CRITICA_NIVEL" CHARACTER VARYING(255),
    "NIVEL_TOTAL" CHARACTER VARYING(255),
    "PENSAMIENTO_CIENTIFICO" INTEGER,
    "PENSAMIENTO_CIENTIFICO_NIVEL" CHARACTER VARYING(255),
    "PRIMER_APELLIDO" CHARACTER VARYING(255) NOT NULL,
    "PRIMER_NOMBRE" CHARACTER VARYING(255) NOT NULL,
    "PROGRAMA" CHARACTER VARYING(255),
    "PUNTAJE_TOTAL" INTEGER,
    "RAZONAMIENTO_CUANTITATIVO" INTEGER,
    "RAZONAMIENTO_CUANTITATIVO_NIVEL" CHARACTER VARYING(255),
    "REGISTRO" CHARACTER VARYING(255),
    "SEGUNDO_APELLIDO" CHARACTER VARYING(255),
    "SEGUNDO_NOMBRE" CHARACTER VARYING(255),
    "TELEFONO" CHARACTER VARYING(255),
    "TIPO_DOCUMENTO" CHARACTER VARYING(255)
);            
ALTER TABLE "PUBLIC"."ESTUDIANTES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("ID");  
-- 35 +/- SELECT COUNT(*) FROM PUBLIC.ESTUDIANTES;            
INSERT INTO "PUBLIC"."ESTUDIANTES" VALUES
(1, 206, 'Nivel 4', 128, 'Nivel 2', 'barbosa@example.com', 197, 'Nivel 4', '123456789', 185, 'Nivel 3', 'B1', 202, 'Nivel 4', 'Nivel 4', 160, 'Nivel 3', 'Barbosa', 'David', U&'Ingenier\00eda de Sistemas', 200, 182, 'Nivel 3', 'EK20183007722', '', '', '3001234567', 'CC'),
(2, 163, 'Nivel 3', 125, 'Nivel 1', 'quintero@example.com', 136, 'Nivel 2', '987654321', 182, 'Nivel 3', 'B2', 179, 'Nivel 3', 'Nivel 3', 144, 'Nivel 2', 'Quintero', 'Alejandro', U&'Ingenier\00eda de Sistemas', 165, 151, 'Nivel 2', 'EK20183140703', '', '', '3001234568', 'CC'),
(3, 142, 'Nivel 2', 159, 'Nivel 3', 'parra@example.com', 148, 'Nivel 2', '111111111', 167, 'Nivel 3', 'A2', 182, 'Nivel 3', 'Nivel 3', 132, 'Nivel 2', 'Parra', 'Angie', U&'Ingenier\00eda de Sistemas', 164, 172, 'Nivel 3', 'EK20183040545', '', '', '3001234569', 'CC'),
(4, 149, 'Nivel 2', 146, 'Nivel 2', 'anaya@example.com', 171, 'Nivel 3', '222222222', 174, 'Nivel 3', 'A2', 157, 'Nivel 3', 'Nivel 3', 127, 'Nivel 2', 'Anaya', 'Lina', U&'Ingenier\00eda de Sistemas', 160, 199, 'Nivel 4', 'EK20183025381', '', '', '3001234570', 'CC'),
(5, 157, 'Nivel 3', 198, 'Nivel 4', 'flor@example.com', 160, 'Nivel 3', '333333333', 168, 'Nivel 3', 'A2', 147, 'Nivel 2', 'Nivel 3', 114, 'Nivel 1', 'Florez', 'Sandra', U&'Ingenier\00eda de Sistemas', 160, 153, 'Nivel 2', 'EK20183025335', '', '', '3001234571', 'CC'),
(6, 140, 'Nivel 2', 179, 'Nivel 3', 'garcia1@example.com', 142, 'Nivel 2', '444444444', 128, 'Nivel 2', 'A1', 158, 'Nivel 3', 'Nivel 3', 121, 'Nivel 1', 'Garcia', 'Milena', U&'Ingenier\00eda de Sistemas', 157, 172, 'Nivel 3', 'EK20183122648', '', '', '3001234572', 'CC'),
(7, 172, 'Nivel 3', 115, 'Nivel 1', 'manosalva@example.com', 119, 'Nivel 1', '555555555', 142, 'Nivel 2', 'A2', 159, 'Nivel 3', 'Nivel 2', 118, 'Nivel 1', 'Manosalva', 'Mateo', U&'Ingenier\00eda de Sistemas', 153, 152, 'Nivel 2', 'EK20183064605', '', '', '3001234573', 'CC'),
(8, 169, 'Nivel 3', 132, 'Nivel 2', 'mendoza@example.com', 171, 'Nivel 3', '666666666', 173, 'Nivel 3', 'B2', 125, 'Nivel 1', 'Nivel 2', 127, 'Nivel 2', 'Mendoza', 'Lucas', U&'Ingenier\00eda de Sistemas', 151, 123, 'Nivel 1', 'EK20183187351', '', '', '3001234574', 'CC'),
(9, 171, 'Nivel 3', 86, 'Nivel 1', 'beltran@example.com', 142, 'Nivel 2', '777777777', 162, 'Nivel 3', 'A2', 160, 'Nivel 3', 'Nivel 2', 125, 'Nivel 1', 'Beltran', 'Bruno', U&'Ingenier\00eda de Sistemas', 150, 187, 'Nivel 3', 'EK20183233820', '', '', '3001234575', 'CC'),
(10, 158, 'Nivel 3', 175, 'Nivel 3', 'santamaria@example.com', 125, 'Nivel 1', '888888888', 162, 'Nivel 3', 'A1', 145, 'Nivel 2', 'Nivel 2', 76, 'Nivel 1', 'Santamaria', 'Elias', U&'Ingenier\00eda de Sistemas', 150, 149, 'Nivel 2', 'EK20183030016', '', '', '3001234576', 'CC'),
(11, 129, 'Nivel 2', 209, 'Nivel 4', 'sanchez@example.com', 136, 'Nivel 2', '999999999', 137, 'Nivel 2', 'A2', 117, 'Nivel 1', 'Nivel 2', 125, 'Nivel 1', 'Sanchez', 'Ana', U&'Ingenier\00eda de Sistemas', 149, 143, 'Nivel 2', 'EK20183047073', '', '', '3001234577', 'CC'),
(12, 164, 'Nivel 3', 93, 'Nivel 1', 'romero@example.com', 154, 'Nivel 2', '101010101', 174, 'Nivel 3', 'A1', 155, 'Nivel 2', 'Nivel 2', 130, 'Nivel 2', 'Romero', 'Samanta', U&'Ingenier\00eda de Sistemas', 146, 183, 'Nivel 3', 'EK20183236451', '', '', '3001234578', 'CC'),
(13, 135, 'Nivel 2', 125, 'Nivel 1', 'luna@example.com', 165, 'Nivel 3', '111122222', 176, 'Nivel 3', 'A2', 138, 'Nivel 2', 'Nivel 2', 128, 'Nivel 2', 'Luna', 'Diego', U&'Ingenier\00eda de Sistemas', 141, 157, 'Nivel 3', 'EK20183041714', '', '', '3001234579', 'CC'),
(14, 150, 'Nivel 2', 150, 'Nivel 2', 'triana@example.com', 131, 'Nivel 2', '222233333', 148, 'Nivel 2', 'A1', 145, 'Nivel 2', 'Nivel 2', 129, 'Nivel 2', 'Triana', 'Enzo', U&'Ingenier\00eda de Sistemas', 141, 136, 'Nivel 2', 'EK20183187801', '', '', '3001234580', 'CC'),
(15, 132, 'Nivel 2', 128, 'Nivel 2', 'suarez@example.com', 125, 'Nivel 1', '333344444', 130, 'Nivel 2', 'A2', 146, 'Nivel 2', 'Nivel 2', 110, 'Nivel 1', 'Suarez', 'Sofia', U&'Ingenier\00eda de Sistemas', 140, 146, 'Nivel 2', 'EK20183176566', '', '', '3001234581', 'CC');            
INSERT INTO "PUBLIC"."ESTUDIANTES" VALUES
(16, 146, 'Nivel 2', 129, 'Nivel 2', 'garcia2@example.com', 131, 'Nivel 2', '444455555', 109, 'Nivel 1', 'A1', 148, 'Nivel 2', 'Nivel 2', 107, 'Nivel 1', 'Garnica', 'Nicol', U&'Ingenier\00eda de Sistemas', 139, 138, 'Nivel 2', 'EK20183204427', '', '', '3001234582', 'CC'),
(17, 147, 'Nivel 2', 153, 'Nivel 2', 'pinzon@example.com', 160, 'Nivel 3', '555566666', 145, 'Nivel 2', 'A1', 127, 'Nivel 2', 'Nivel 2', 143, 'Nivel 2', 'Pinzon', 'Alonzo', U&'Ingenier\00eda de Sistemas', 138, 123, 'Nivel 1', 'EK20183196280', '', '', '3001234583', 'CC'),
(18, 100, 'Nivel 1', 166, 'Nivel 3', 'jaimes@example.com', 113, 'Nivel 1', '666677777', 100, 'Nivel 1', 'A1', 124, 'Nivel 1', 'Nivel 2', 105, 'Nivel 1', 'Jaimes', 'Samuel', U&'Ingenier\00eda de Sistemas', 137, 157, 'Nivel 3', 'EK20183173799', '', '', '3001234584', 'CC'),
(19, 118, 'Nivel 1', 165, 'Nivel 3', 'nino@example.com', 154, 'Nivel 2', '777788888', 146, 'Nivel 2', 'A-', 136, 'Nivel 2', 'Nivel 2', 122, 'Nivel 1', U&'Ni\00f1o', 'Fernanda', U&'Ingenier\00eda de Sistemas', 134, 137, 'Nivel 2', 'EK20183009565', '', '', '3001234585', 'CC'),
(20, 150, 'Nivel 2', 139, 'Nivel 2', 'fabian@example.com', 94, 'Nivel 1', '888899999', 102, 'Nivel 1', 'A-', 168, 'Nivel 3', 'Nivel 2', 123, 'Nivel 1', 'Reyes', 'Claudia', U&'Ingenier\00eda de Sistemas', 133, 93, 'Nivel 1', 'EK20183117756', '', '', '3001234586', 'CC'),
(21, 104, 'Nivel 1', 116, 'Nivel 1', 'hernandez@example.com', 154, 'Nivel 2', '121212121', 158, 'Nivel 3', 'A1', 136, 'Nivel 2', 'Nivel 2', 125, 'Nivel 1', 'Hernandez', 'Miguel', U&'Ingenier\00eda de Sistemas', 132, 166, 'Nivel 3', 'EK20183044579', '', '', '3001234587', 'CC'),
(22, 121, 'Nivel 1', 149, 'Nivel 2', 'larios@example.com', 165, 'Nivel 3', '232323232', 101, 'Nivel 1', 'A1', 129, 'Nivel 2', 'Nivel 2', 102, 'Nivel 1', 'Gomez', 'Sebastian', U&'Ingenier\00eda de Sistemas', 131, 123, 'Nivel 1', 'EK20183045760', '', '', '3001234588', 'CC'),
(23, 111, 'Nivel 1', 127, 'Nivel 2', 'calderon@example.com', 94, 'Nivel 1', '343434343', 65, 'Nivel 1', 'A1', 134, 'Nivel 2', 'Nivel 2', 112, 'Nivel 1', 'Calderon', 'Kiara', U&'Ingenier\00eda de Sistemas', 130, 147, 'Nivel 2', 'EK20183034044', '', '', '3001234589', 'CC'),
(24, 131, 'Nivel 2', 96, 'Nivel 1', 'villarreal@example.com', 131, 'Nivel 2', '454545454', 122, 'Nivel 1', 'A1', 114, 'Nivel 1', 'Nivel 2', 112, 'Nivel 1', 'Villareal', 'Laura', U&'Ingenier\00eda de Sistemas', 129, 162, 'Nivel 3', 'EK20183041521', '', '', '3001234590', 'CC'),
(25, 149, 'Nivel 2', 81, 'Nivel 1', 'restrepo1@example.com', 142, 'Nivel 2', '565656565', 127, 'Nivel 2', 'A1', 126, 'Nivel 2', 'Nivel 2', 136, 'Nivel 2', 'Restrepo', 'Juan', U&'Ingenier\00eda de Sistemas', 126, 134, 'Nivel 2', 'EK20183027436', '', '', '3001234591', 'CC'),
(26, 92, 'Nivel 1', 124, 'Nivel 1', 'caceres@example.com', 131, 'Nivel 2', '676767676', 132, 'Nivel 2', 'A2', 108, 'Nivel 1', 'Nivel 1', 104, 'Nivel 1', 'Caceres', 'Julian', U&'Ingenier\00eda de Sistemas', 125, 135, 'Nivel 2', 'EK20183031592', '', '', '3001234592', 'CC'),
(27, 88, 'Nivel 1', 131, 'Nivel 2', 'tabares@example.com', 148, 'Nivel 2', '787878787', 136, 'Nivel 2', 'A2', 107, 'Nivel 1', 'Nivel 1', 112, 'Nivel 1', 'Tabares', 'Daniela', U&'Ingenier\00eda de Sistemas', 124, 131, 'Nivel 2', 'EK20183004153', '', '', '3001234593', 'CC'),
(28, 112, 'Nivel 1', 166, 'Nivel 3', 'naranjo@example.com', 119, 'Nivel 1', '898989898', 135, 'Nivel 2', 'A-', 113, 'Nivel 1', 'Nivel 1', 117, 'Nivel 1', 'Naranjo', 'Karol', U&'Ingenier\00eda de Sistemas', 122, 113, 'Nivel 1', 'EK20183030783', '', '', '3001234594', 'CC'),
(29, 107, 'Nivel 1', 119, 'Nivel 1', 'prada@example.com', 119, 'Nivel 1', '909090909', 83, 'Nivel 1', 'A1', 137, 'Nivel 2', 'Nivel 1', 104, 'Nivel 1', 'Prada', 'Felipe', U&'Ingenier\00eda de Sistemas', 122, 125, 'Nivel 1', 'EK20183024754', '', '', '3001234595', 'CC'),
(30, 86, 'Nivel 1', 95, 'Nivel 1', 'vargas@example.com', 119, 'Nivel 1', '112233445', 149, 'Nivel 2', 'A-', 151, 'Nivel 2', 'Nivel 1', 103, 'Nivel 1', 'Vargas', 'Daniel', U&'Ingenier\00eda de Sistemas', 114, 120, 'Nivel 1', 'EK20183186200', '', '', '3001234596', 'CC');    
INSERT INTO "PUBLIC"."ESTUDIANTES" VALUES
(31, 103, 'Nivel 1', 109, 'Nivel 1', 'torres@example.com', 80, 'Nivel 1', '223344556', 102, 'Nivel 1', 'A1', 104, 'Nivel 1', 'Nivel 1', 135, 'Nivel 2', 'Torres', 'Camila', U&'Ingenier\00eda de Sistemas', 113, 105, 'Nivel 1', 'EK20183182410', '', '', '3001234597', 'CC'),
(32, 102, 'Nivel 1', 128, 'Nivel 2', 'ortiz@example.com', 125, 'Nivel 1', '334455667', 130, 'Nivel 2', 'A-', 107, 'Nivel 1', 'Nivel 1', 111, 'Nivel 1', 'Ortiz', 'Maira', U&'Ingenier\00eda de Software', 107, 81, 'Nivel 1', 'EK20183213735', '', '', '3001234598', 'CC'),
(33, 110, 'Nivel 1', 134, 'Nivel 2', 'villamizar@example.com', 119, 'Nivel 1', '445566778', 83, 'Nivel 1', 'A-', 92, 'Nivel 1', 'Nivel 1', 107, 'Nivel 1', 'Villamizar', 'Gustavo', U&'Ingenier\00eda de Sistemas', 106, 96, 'Nivel 1', 'EK20183065220', '', '', '3001234599', 'CC'),
(34, 105, 'Nivel 1', 0, 'Nivel 1', 'restrepo2@example.com', 131, 'Nivel 2', '556677889', 157, 'Nivel 3', 'A1', 122, 'Nivel 1', 'Nivel 1', 96, 'Nivel 1', 'Restrepo', 'Andres', U&'Ingenier\00eda de Sistemas', 96, 117, 'Nivel 1', 'EK20183028123', '', '', '3001234600', 'CC'),
(35, 123, 'Nivel 1', 145, 'Nivel 2', 'alejobarajas2006@gmail.com', 155, 'Nivel 2', '1097492951', 219, 'Nivel 4', 'A2', 200, 'Nivel 3', 'Nivel 2', 135, 'Nivel 2', 'Barajas', 'David', U&'Ingenier\00eda de Sistemas', 126, 200, 'Nivel 3', 'EK20183236452', 'Reyes', 'Alejandro', '3004576167', 'CC');       
ALTER TABLE "PUBLIC"."ESTUDIANTES" ADD CONSTRAINT "PUBLIC"."UK30Y1JWX51RQOPMYOGOL0KJTTX" UNIQUE NULLS DISTINCT ("DOCUMENTO"); 
ALTER TABLE "PUBLIC"."USUARIOS" ADD CONSTRAINT "PUBLIC"."UKM2DVBWFGE291EUVMK6VKKOCAO" UNIQUE NULLS DISTINCT ("USERNAME");     
